services:

  #1 Database
  Postgres:
    image: postgres:14.22-trixie
    container_name: forge_db
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
      POSTGRES_DB: forge_db
    ports:
      - "5432:5432"

  #2 Backend
  Backend:
    image: springboot/8-jdk-alpine-maven
    container_name: forge_backend
    ports:
      - "8080:8080"
      - "5005:5005" #for debugging
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/forge_db

  #Frontend
  Frontend:
    image: openeuler/react
    container_name: forge_frontend
    ports:
      - "3000:3000"
