spring.application.name=talent-acquisition-engine


# Affinda Credentials
affinda.api.key=aff_408a12b2dd793ac770057e54ab28ae194b045518
affinda.workspace.id=frmLiRfF


# GCP Storage Credentials (from our earlier setup)
gcp.bucket.name=your_gcp_bucket_name
