spring.application.name=talent-acquisition-engine


# Affinda Credentials
affinda.api.key=aff_408a12b2dd793ac770057e54ab28ae194b045518
affinda.workspace.id=frmLiRfF


# GCP Storage Credentials (from our earlier setup)
gcp.bucket.name=your_gcp_bucket_name

spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=candidate-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=org.example.externalcandidate.externalCandidate.event.CandidateCreatedEvent
