server.port=8084
spring.application.name=talent-acquisition-engine
# Affinda Credentials
affinda.api.key=aff_408a12b2dd793ac770057e54ab28ae194b045518
affinda.workspace.id=frmLiRfF
# GCP Storage Credentials (from our earlier setup)
gcp.bucket.name=your_gcp_bucket_name
spring.kafka.bootstrap-servers=localhost:9092
# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Consumer
spring.kafka.consumer.group-id=candidate-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.forge.talentacquisitionengine.candidateService.externalCandidate.event.CandidateCreatedEvent
#Google Calendar
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/calendar

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/forge_talent
spring.datasource.username=forge_user
spring.datasource.password=forge_dev_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
# JPA


# Flyway
